#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TAILTRAIL_ENTRY = ROOT / "scripts" / "tailtrail.py"
DEFAULT_HELLO_ALIAS = "hello"


def default_bin_dir() -> Path:
    return Path.home() / ".local" / "bin"


def path_entries() -> list[Path]:
    return [Path(item).expanduser() for item in os.environ.get("PATH", "").split(os.pathsep) if item]


def in_path(directory: Path) -> bool:
    resolved = directory.expanduser().resolve()
    return any(item.expanduser().resolve() == resolved for item in path_entries() if item.exists())


def command_destination(directory: Path, name: str, windows: bool | None = None) -> Path:
    if windows is None:
        windows = os.name == "nt"
    if windows and not name.lower().endswith((".cmd", ".bat")):
        name = f"{name}.cmd"
    return directory / name


def launcher_body(windows: bool | None = None) -> str:
    if windows is None:
        windows = os.name == "nt"
    if windows:
        return "\r\n".join(
            [
                "@echo off",
                "REM Generated by TailTrail. Edit by reinstalling with scripts/install-launcher.py.",
                'set "TAILTRAIL_COMMAND_NAME=tailtrail"',
                f'"{sys.executable}" "{TAILTRAIL_ENTRY}" %*',
                "exit /b %ERRORLEVEL%",
                "",
            ]
        )
    return "\n".join(
    return "\n".join(
        [
            "#!/bin/sh",
            "# Generated by TailTrail. Edit by reinstalling with scripts/install-launcher.py.",
            'TAILTRAIL_COMMAND_NAME="${0##*/}"',
            "export TAILTRAIL_COMMAND_NAME",
            f'exec "{sys.executable}" "{TAILTRAIL_ENTRY.as_posix()}" "$@"',
            "",
        ]
    )


def hello_alias_body(windows: bool | None = None) -> str:
    if windows is None:
        windows = os.name == "nt"
    if windows:
        return "\r\n".join(
            [
                "@echo off",
                "REM Generated by TailTrail. Edit by reinstalling with scripts/install-launcher.py.",
                'if /I not "%~1"=="tailtrail" goto usage',
                'set "TAILTRAIL_COMMAND_NAME=hello tailtrail"',
                f'"{sys.executable}" "{TAILTRAIL_ENTRY}" hello %2 %3 %4 %5 %6 %7 %8 %9',
                "exit /b %ERRORLEVEL%",
                ":usage",
                "echo Usage: hello tailtrail [--quiet] 1>&2",
                "echo This TailTrail shim only handles: hello tailtrail 1>&2",
                "exit /b 2",
                "",
            ]
        )
    return "\n".join(
    return "\n".join(
        [
            "#!/bin/sh",
            "# Generated by TailTrail. Edit by reinstalling with scripts/install-launcher.py.",
            'case "$1" in',
            "  tailtrail|TailTrail|TAILTRAIL|taitrail|TaiTrail|TAITRAIL)",
            "    shift",
            '    TAILTRAIL_COMMAND_NAME="hello tailtrail"',
            "    export TAILTRAIL_COMMAND_NAME",
            f'    exec "{sys.executable}" "{TAILTRAIL_ENTRY.as_posix()}" hello "$@"',
            "    ;;",
            "esac",
            'echo "Usage: hello tailtrail [--quiet]" >&2',
            'echo "This TailTrail shim only handles: hello tailtrail" >&2',
            "exit 2",
            "",
        ]
    )


def write_executable(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def print_plan(destination: Path, hello_destination: Path | None, dry_run: bool, force: bool) -> None:
    print("# TailTrail Launcher Installer")
    print()
    print(f"- TailTrail root: `{ROOT.as_posix()}`")
    print(f"- Launcher path: `{destination.as_posix()}`")
    if hello_destination:
        print(f"- Hello alias path: `{hello_destination.as_posix()}`")
    print(f"- Mode: `{'dry-run' if dry_run else 'apply'}`")
    print(f"- Force overwrite: `{force}`")
    print()
    print("The launcher lets users run TailTrail from any repo:")
    print()
    print("```bash")
    print("hello tailtrail")
    print('tailtrail guide "tell me important features of this repo"')
    print('tailtrail start "fix Sonar issue and prepare PR" --changed path/to/file')
    print("```")
    if hello_destination:
        print()
        print("The `hello` alias is intentionally narrow: it only handles `hello tailtrail` and delegates to `tailtrail hello`.")
    print()
    if in_path(destination.parent):
        print(f"`{destination.parent.as_posix()}` is already on PATH.")
    else:
        print(f"`{destination.parent.as_posix()}` is not currently on PATH.")
        print("Add it to your shell profile if you want to call `tailtrail` without a full path.")


def install(destination: Path, dry_run: bool, force: bool, hello_alias: str | None) -> int:
    windows = os.name == "nt"
    hello_destination = command_destination(destination.parent, hello_alias, windows) if hello_alias else None
    print_plan(destination, hello_destination, dry_run, force)
    if dry_run:
        return 0
    if destination.exists() and not force:
        print()
        print(f"Launcher already exists: {destination}")
        print("Use --force to overwrite it.")
        return 1
    if hello_destination and hello_destination.exists() and not force:
        print()
        print(f"Hello alias already exists: {hello_destination}")
        print("Use --force to overwrite it, or use --no-hello-alias.")
        return 1
    write_executable(destination, launcher_body(windows))
    print()
    print(f"Installed launcher: {destination}")
    if hello_destination:
        write_executable(hello_destination, hello_alias_body(windows))
        print(f"Installed hello alias: {hello_destination}")
    if not in_path(destination.parent):
        print()
        print("PATH note:")
        print(f"- Add `{destination.parent.as_posix()}` to PATH, or run the launcher by full path.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Install a small `tailtrail` launcher command.")
    parser.add_argument("--bin-dir", type=Path, default=default_bin_dir(), help="Directory where the launcher should be written.")
    parser.add_argument("--name", default="tailtrail", help="Launcher command name.")
    parser.add_argument("--hello-alias", default=DEFAULT_HELLO_ALIAS, help="Optional command name that makes `hello tailtrail` work.")
    parser.add_argument("--no-hello-alias", action="store_true", help="Install only the main launcher.")
    parser.add_argument("--dry-run", action="store_true", help="Show the install plan without writing files.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing launcher.")
    args = parser.parse_args()

    if not TAILTRAIL_ENTRY.exists():
        raise SystemExit(f"TailTrail entrypoint not found: {TAILTRAIL_ENTRY}")
    if "/" in args.name or args.name in {"", ".", ".."}:
        raise SystemExit("--name must be a simple command name, such as tailtrail")
    if args.hello_alias and ("/" in args.hello_alias or args.hello_alias in {".", ".."}):
        raise SystemExit("--hello-alias must be a simple command name, such as hello")
    if args.hello_alias == "":
        raise SystemExit("--hello-alias cannot be empty; use --no-hello-alias instead")
    destination = command_destination(args.bin_dir.expanduser().resolve(), args.name)
    hello_alias = None if args.no_hello_alias else args.hello_alias
    return install(destination, args.dry_run, args.force, hello_alias)


if __name__ == "__main__":
    raise SystemExit(main())
